=== f-babar/unconventional-malware-detector/hz-schema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <!-- Specifications for HazelCast In-Memory Malware -->
    
    <xs:element name="hz-specification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hz-member" type="memberType"/>
                <xs:element name="hz-client" type="clientType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!--    Schema for HazelCast Members    -->
    
    <xs:complexType name="memberType">
        <xs:sequence>
            <xs:element name="new-member">
                <xs:complexType>
                    <xs:attribute name="time-seconds" type="xs:int" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="max-members" type="xs:int"/>
            <xs:element name="time-to-leave" type="xs:string"/>
            <xs:element name="http-connections">
                <xs:complexType>
                    <xs:attribute name="max" type="xs:int" use="optional" />
                    <xs:attribute name="min" type="xs:int" use="optional"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="update-records" type="xs:boolean"/>
            <xs:element name="read-all-records" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    
    <!--    Schema for HazelCast Clients    --> 
    
    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element name="check-ip" type="xs:boolean"/>
            <xs:element name="update-records" type="xs:boolean"/>
            <xs:element name="read-all-records" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType >
</xs:schema>

=== f-babar/unconventional-malware-detector/hz-specifications.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Application based specifications to detect in-memory malware with 
    Unconventional attack techniques in HazelCast platform   
-->
<hz-specification
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="hz-schema.xsd">
    
    <hz-member>
        <max-members>4</max-members>
        <time-to-leave>10000</time-to-leave>
        <update-records>true</update-records>
        <read-all-records>false</read-all-records>
        <http-connections max="2" min="1"></http-connections>
    </hz-member>
  
    <hz-client>
       <check-ip>true</check-ip>
        <update-records>true</update-records>
        <read-all-records>false</read-all-records>
        <check-ip>true</check-ip>
        <update-records>true</update-records>
        <read-all-records>false</read-all-records>
    </hz-client>
</hz-specification>
